require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - Gemfile
    - Gemfile.lock
    - spec/**/*
Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
    Max: 20